"""create check problem table

Revision ID: 7189d9980d59
Revises: 992128bd5124
Create Date: 2026-08-31 10:54:21.156090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7189d9980d59'
down_revision: Union[str, Sequence[str], None] = '992128bd5124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_problem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('decomposed', sa.Integer(), nullable=False),
    sa.Column('revised', sa.Integer(), nullable=False),
    sa.Column('assessed', sa.Integer(), nullable=False),
    sa.Column('check_department', sa.String(length=255), nullable=False),
    sa.Column('check_person', sa.String(length=255), nullable=False),
    sa.Column('check_type', sa.Integer(), nullable=False),
    sa.Column('check_way', sa.Integer(), nullable=False),
    sa.Column('check_start_time', sa.DateTime(), nullable=False),
    sa.Column('check_end_time', sa.DateTime(), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=False),
    sa.Column('problem_item', sa.String(length=255), nullable=False),
    sa.Column('consequences', sa.String(length=255), nullable=False),
    sa.Column('risk_type', sa.String(length=255), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('problem_classify', sa.Integer(), nullable=False),
    sa.Column('problem_label', sa.Integer(), nullable=False),
    sa.Column('problem_extra_points', sa.String(length=50), nullable=False),
    sa.Column('problem_type', sa.String(length=255), nullable=False),
    sa.Column('red_line', sa.Integer(), nullable=False),
    sa.Column('problem_position', sa.String(length=255), nullable=False),
    sa.Column('implement_department', sa.String(length=255), nullable=False),
    sa.Column('duty_department', sa.String(length=255), nullable=False),
    sa.Column('other_classify', sa.String(length=255), nullable=False),
    sa.Column('cross_unit', sa.Integer(), nullable=False),
    sa.Column('business_guidance', sa.Integer(), nullable=False),
    sa.Column('outside', sa.Integer(), nullable=False),
    sa.Column('problem_description', sa.String(length=255), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('rectification_requirements', sa.String(length=255), nullable=True),
    sa.Column('rectification_person', sa.String(length=50), nullable=True),
    sa.Column('rectification_time', sa.DateTime(), nullable=True),
    sa.Column('rectification_description', sa.String(length=255), nullable=True),
    sa.Column('responsible_person', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('close_issue_person', sa.String(length=50), nullable=True),
    sa.Column('close_issue_evaluate', sa.String(length=255), nullable=True),
    sa.Column('close_issue_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_problem')
    # ### end Alembic commands ###
